apiVersion: v2
description: Hephy Workflow Controller (API).
home: https://github.com/teamhephy/controller
maintainers:
- email: team@teamhephy.com
  name: Team Hephy
name: controller
version: 2.22.3
