apiVersion: v1
description: Deis dockerbuilder builds your app from a Dockerfile inside a Kubernetes
  pod, used by Deis Workflow.
home: https://github.com/deisthree/dockerbuilder
maintainers:
- email: engineering@deis.com
  name: Deis Team
name: dockerbuilder
version: 2.8.4
