apiVersion: v1
kind: ConfigMap
metadata:
  name: slugbuilder-config
  labels:
    heritage: deis
data:
  image: "{{.Values.org}}/slugbuilder:{{.Values.docker_tag}}"
  pullpolicy: {{ .Values.pull_policy }}
