apiVersion: v2
description: A Redis database for use inside a Kubernetes cluster.
home: https://github.com/teamhephy/redis
maintainers:
- email: team@teamhephy.com
  name: Team Hephy
name: redis
version: 2.4.5
