apiVersion: v2
description: Minio Object Storage in Kubernetes, used by Hephy Workflow.
home: https://github.com/teamhephy/minio
maintainers:
- email: team@teamhephy.com
  name: Team Hephy
name: minio
version: 2.4.7
