apiVersion: v2
description: Log shipping mechanism for Hephy Workflow.
home: https://github.com/teamhephy/fluentd
maintainers:
- email: team@teamhephy.com
  name: Team Hephy
name: fluentd
version: 2.15.3
