apiVersion: v2
description: 'Hephy Workflow Manager: Cluster First Aid'
home: https://github.com/teamhephy/workflow-manager
maintainers:
- email: team@teamhephy.com
  name: Team Hephy
name: workflow-manager
version: 2.6.4
