apiVersion: v1
description: In-memory log buffer used by Deis Workflow.
home: https://github.com/teamhephy/logger
maintainers:
- email: engineering@deis.com
  name: Deis Team
name: logger
version: 2.5.2
