apiVersion: v1
description: Buildpack application builder for Deis Workflow.
home: https://github.com/teamhephy/slugbuilder
maintainers:
- email: engineering@deis.com
  name: Deis Team
name: slugbuilder
version: 2.8.1
