{{- if eq .Values.global.logger_redis_location "on-cluster" }}
apiVersion: {{ template "APIVersion" . }}
kind: StatefulSet
metadata:
  name: deis-logger-redis
  labels:
    heritage: deis
  annotations:
    component.deis.io/version: {{ .Values.docker_tag }}
spec:
  serviceName: deis-logger-redis
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: deis-logger-redis
  template:
    metadata:
      labels:
        app: deis-logger-redis
    spec:
      containers:
      - name: deis-logger-redis
        image: {{ .Values.org }}/redis:{{ .Values.docker_tag }}
        imagePullPolicy: {{ .Values.pull_policy }}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
        resources:
          limits:
{{- if (.Values.limits_cpu) }}
            cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
            memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
        command: ["/bin/boot", "--port", "{{.Values.port}}"]
        ports:
        - containerPort: {{.Values.port}}
        volumeMounts:
        - name: logger-redis-creds
          mountPath: /var/run/secrets/deis/redis/creds
      volumes:
      - name: logger-redis-creds
        secret:
          secretName: logger-redis-creds
{{- end }}
