apiVersion: v2
description: Monitoring for Hephy Workflow.
home: https://github.com/teamhephy/monitor/tree/master/influxdb
maintainers:
- email: team@teamhephy.com
  name: Team Hephy
name: influxdb
version: 2.11.6
