name: Publish OCI Chart (workflow)

on:
  push:
    tags:
      - 'minio-*'

env:
  OCI_REPO: "kingdonb/hephy-workflow-beta/minio"

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          # BRANCH=${GITHUB_REF##*/}
          # TS=$(date +%s)
          # REVISION=${GITHUB_SHA::8}
          # BUILD_ID="${BRANCH}-${REVISION}-${TS}"
          # LATEST_ID=canary
          if [[ $GITHUB_REF == refs/tags/minio-* ]]; then
            BUILD_ID=${GITHUB_REF/refs\/tags\/minio-/}
            LATEST_ID=latest-minio
          fi
          echo BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_OUTPUT
          echo BUILD_ID=${BUILD_ID} >> $GITHUB_OUTPUT
          echo LATEST_ID=${LATEST_ID} >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.4.0
        with:
          name: minio
          repository: ${OCI_REPO}
          tag: ${{ steps.prep.outputs.BUILD_ID }}
          path: minio
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
