name: Publish OCI Chart (slugbuilder)

on:
  push:
    tags:
      - 'slugbuilder-*'

env:
  OCI_REPO: "kingdonb/hephy-workflow-beta"

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          # BRANCH=${GITHUB_REF##*/}
          # TS=$(date +%s)
          # REVISION=${GITHUB_SHA::8}
          # BUILD_ID="${BRANCH}-${REVISION}-${TS}"
          # LATEST_ID=canary
          if [[ $GITHUB_REF == refs/tags/slugbuilder-* ]]; then
            BUILD_ID=${GITHUB_REF/refs\/tags\/slugbuilder-/}
            LATEST_ID=latest-slugbuilder
          fi
          echo BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_OUTPUT
          echo BUILD_ID=${BUILD_ID} >> $GITHUB_OUTPUT
          echo LATEST_ID=${LATEST_ID} >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.4.0
        with:
          name: slugbuilder
          repository: ${OCI_REPO}
          tag: ${{ steps.prep.outputs.BUILD_ID }}
          path: slugbuilder
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
